# ruff.toml
target-version = "py310"
extend-exclude = [".venv", "build", "dist", ".github", "__pycache__"]

[lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[format]
quote-style = "single"
